(define (make-from-mag-ang  mag ang)
  (define (dispatch op)
    (cond ((eq? op 'magnitude) magnitude)
          ((eq? op 'angle) angle)
          ((eq? op 'real-part) 
           (* (magnitude z) (cos (angle z))))
          ((eq? op 'angle) 
           (* (magnitude z) (sin (angle z))))
          (else (error "Unknown op -- MAKE-FROM-MAG-ANG" op))))
  dispatch)